<a href="https://colab.research.google.com/github/KayalvizhiT513/API-for-Sapota-Yield-Agriculture-using-FastAPI/blob/main/EigenValuesVectors_Notebook2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sp

In [2]:
# Define the matrix A
A = np.array([[5, 2, 0],
      [2, 5, 0],
      [-3, 4, 6]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues: [6. 7. 3.]
Eigenvectors:
[[ 0.          0.57735027  0.36650833]
 [ 0.          0.57735027 -0.36650833]
 [ 1.          0.57735027  0.85518611]]


In [4]:
# Concatenate eigenvectors into a matrix
eig_matrix = np.column_stack(eigenvectors)

# Convert the matrix to sympy format
eig_matrix_sympy = sp.Matrix(eig_matrix)

# Compute the reduced row echelon form (RREF)
rref = eig_matrix_sympy.rref()
print("RREF:")
print(rref[0])

# Find the rank of the matrix
rank = eig_matrix_sympy.rank()
print("Rank of the RREF:", rank)

# Check if eigenvectors are linearly independent
if rank == min(A.shape):
    print("The eigenvectors corresponding to distinct eigenvalues are linearly independent.")
else:
    print("The eigenvectors corresponding to distinct eigenvalues are linearly dependent.")


RREF:
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
Rank of the RREF: 3
The eigenvectors corresponding to distinct eigenvalues are linearly independent.
